server:
  port: 8086
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    # gateway??
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      # ????
      routes:
        - id: order_route # 路由名字
          uri: lb://wisdomHub-learn  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/assignment/**
        - id: order_route # 路由名字
          uri: lb://wisdomHub-learn  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/course/**
        - id: order_route # 路由名字
          uri: lb://wisdomHub-learn  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/question/**
        - id: order_route # 路由名字
          uri: lb://wisdomHub-learn  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/resource/**
        - id: wisdomHub-user # 路由名字
          uri: lb://wisdomHub-user  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/user/**
        - id: wisdomHub-courseActivity # 路由名字
          uri: lb://wisdomHub-courseActivity  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/activity/**
            - Path=/resource/**
        - id: order_route # 路由名字
          uri: lb://wisdomHub-learn  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/testPaper/**
        - id: wisdomHub-user # 路由名字
          uri: lb://wisdomHub-user  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/user/**
        - id: wisdomHub-courseActivity # 路由名字
          uri: lb://wisdomHub-courseActivity  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/activity/**
        - id: wisdomHub-courseActivity # 路由名字
          uri: lb://wisdomHub-courseActivity  # lb是负载均衡，sentinel是注册中心要转发到的服务的端口对应的注册名
          predicates:
            - Path=/class/**

#            - Path=/course/**
#            - Path=/question/**
#            - Path=/resource/** # 断言，地址含user的就会转发
#当访问localhost:8820/user/getUserById时，转发到注册中心服务名称为sentinel的端口
#localhost:9005/getUserById
#或localhost:9006/getUserById

