server:
  port: 8084
spring:
  application:
    name: wisdomHub-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors: # 定义全局CORS配置
        cors-configurations: # CORS配置的具体定义
          '[/**]': # 匹配所有路径的路由
            allowedMethods: "*" # 允许所有HTTP方法
            allowedHeaders: "*" # 允许所有请求头
            allowedOriginPatterns: "*" # 允许来自所有源的请求
            allowCredentials: true # 允许携带凭证的请求
            exposedHeaders: # 定义要暴露给客户端的请求头
              - Authorization # 暴露Authorization请求头
              - Authorization-Refresh # 暴露Authorization-Refresh请求头


      routes:
        - id: wisdomHub-teacher
          uri: lb://wisdomHub-teacher  # 路由的目标地址 lb是负载均衡，后面跟服务名称(推荐)
          predicates:
            - Path=/teacher/**
          filters:
#            - StripPrefix=1
        - id: cloudView-testPaper
          uri: lb://cloudView-testPaper
          predicates:
            - Path=/examPaper/**,/AI/**
          filters:
        #            - StripPrefix=1
        - id: cloudView-testPaper
          uri: lb://cloudView-testPaper
          predicates:
            - Path=/examPaper/**
          filters:
        #            - StripPrefix=1
        - id: cloudView-examAnalysis
          uri: lb://cloudView-examAnalysis
          predicates:
            - Path=/examAnalysis/**
          filters:

  main:
    web-application-type: reactive
    allow-circular-references: true
