server:
  port: 9081

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wisdom_hub?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  application:
    name: wisdomHub-learn
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  neo4j:
    authentication:
      username: neo4j
      password: 123456
    uri: neo4j://192.168.150.101:7687


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml