server:
  port: 9081

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wisdom_hub?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
  application:
    name: wisdomHub-learn
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  neo4j:
    authentication:
      username: neo4j
      password: 123456
    uri: bolt://${neo4j-addr:localhost:7687}


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: wisdomHub-learn
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

  protocol:
    name: dubbo
    port: 15511
  consumer:
    timeout: 100000