server:
  port: 9082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wisdom_hub?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  application:
    name: wisdomHub-courseActivity
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# OSS Configuration
aliyun:
  oss:
    access-key: LTAI5tRhLi2QTrErLgi9xG3K
    secret-key: HkWmmg0a5tWzHuOS1QoJME6Xt3Xbj4
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    bucket: yuejuanpt
    market-host: "https://${aliyun.oss.bucket}.${aliyun.oss.endpoint}"