server:
  port: 9082


spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: UTC
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wisdom_hub?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 1234

  application:
    name: wisdomHub-courseActivity
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# OSS Configuration
aliyun:
  oss:
    access-key: LTAI5tRhLi2QTrErLgi9xG3K
    secret-key: HkWmmg0a5tWzHuOS1QoJME6Xt3Xbj4
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    bucket: yuejuanpt
    market-host: "https://${aliyun.oss.bucket}.${aliyun.oss.endpoint}"